[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[networking]
tcpProxies = [
  { applicationPort = 27015, externalPort = 27015 },
  { applicationPort = 27016, externalPort = 27016 },
  { applicationPort = 27017, externalPort = 27017 },
  { applicationPort = 27018, externalPort = 27018 },
  { applicationPort = 27019, externalPort = 27019 }
]
